name: Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # https://github.com/actions/setup-node
      - name: Node Setup
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install
        run: npm install

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist/app # The folder the action should deploy.
